import type { ITerminalOptions } from "@xterm/xterm";

export const terminalOptions: ITerminalOptions = {
  theme: {
    background: "#050A0F",
    foreground: "#00FF41",
    cursor: "#00FF41",
    cursorAccent: "#050A0F",
    black: "#050A0F",
    brightBlack: "#1A2A1A",
    green: "#00FF41",
    brightGreen: "#80FF80",
    cyan: "#00D4FF",
    brightCyan: "#80E8FF",
    white: "#E0E6ED",
    brightWhite: "#FFFFFF",
    blue: "#0066FF",
    brightBlue: "#5599FF",
    yellow: "#FFD700",
    brightYellow: "#FFEC80",
    red: "#FF4444",
    brightRed: "#FF8888",
    magenta: "#CC44FF",
    brightMagenta: "#DD88FF",
  },
  fontSize: 12,
  fontFamily: '"JetBrains Mono", "Fira Code", monospace',
  fontWeight: "normal",
  letterSpacing: 0,
  lineHeight: 1.4,
  cursorStyle: "block",
  cursorBlink: true,
  scrollback: 200,
  convertEol: true,
  disableStdin: false,
};
