import type { ITerminalOptions } from "@xterm/xterm";

export const terminalOptions: ITerminalOptions = {
  theme: {
    background: "rgba(0,0,0,0)",
    foreground: "#E6E6E6",
    cursor: "#367BF0",
    cursorAccent: "#23252E",
    black: "#1F2229",
    brightBlack: "#5A5D68",
    red: "#D41919",
    brightRed: "#EC0101",
    green: "#5EBDAB",
    brightGreen: "#47D4B9",
    yellow: "#FEA44C",
    brightYellow: "#FF8A18",
    blue: "#367BF0",
    brightBlue: "#277FFF",
    magenta: "#9755B3",
    brightMagenta: "#962AC3",
    cyan: "#49AEE6",
    brightCyan: "#05A1F7",
    white: "#E6E6E6",
    brightWhite: "#FFFFFF",
  },
  fontSize: 14,
  fontFamily: 'ui-monospace, Menlo, Monaco, Consolas, "Liberation Mono", "DejaVu Sans Mono", "Courier New", monospace',
  fontWeight: "normal",
  letterSpacing: 0,
  lineHeight: 1.5,
  cursorStyle: "block",
  cursorBlink: true,
  scrollback: 400,
  convertEol: true,
  disableStdin: false,
  allowTransparency: true,
};
