name: Deploy Backend to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Check for backend changes
      id: check_changes
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q "^backend/"; then
          echo "Backend changes detected"
          echo "backend_changed=true" >> $GITHUB_OUTPUT
        else
          echo "No backend changes detected"
          echo "backend_changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Navigate to backend and build
      if: steps.check_changes.outputs.backend_changed == 'true'
      run: |
        echo "Building backend project..."
        cd backend
        
        # Install dependencies if package.json exists
        if [ -f "package.json" ]; then
          echo "Installing Node.js dependencies..."
          npm install
        fi
        
        # Build the project if build script exists
        if grep -q '"build"' package.json 2>/dev/null; then
          echo "Running build command..."
          npm run build
        fi
        
        # Show build completion
        echo "Backend build completed successfully"
        ls -la
    
    - name: Skip deployment
      if: steps.check_changes.outputs.backend_changed == 'false'
      run: |
        echo "No backend changes detected. Skipping deployment."
